from . import person_abstract
from . import hospital_patient
from . import hospital_doctor
from . import hospital_diagnosis
from . import hospital_contact_person
from . import hospital_category_diseases
from . import hospital_diseases
from . import hospital_visiting_doctor
from . import hospital_history_personal_doctor